// utils/iconCategories.ts
export interface IconCategory {
  name: string;
  icons: string[];
}

export const iconCategories: IconCategory[] = [
  {
    name: "Activities",
    icons: [
      "briefcase-outline",
      "mic-outline",
      "call-outline",
      "cart-outline",
      "boat-outline",
      "home-outline",
      "bag-outline",
      "water-outline",
      "bed-outline",
      "document-text-outline",
      "book-outline",
      "library-outline",
      "code-slash-outline",
      "code-working-outline",
      "locate-outline",
      "grid-outline",
      "game-controller-outline",
      "headset-outline",
      "leaf-outline",
      "flame-outline",
      "phone-portrait-outline",
      "newspaper-outline",
      "bulb-outline",
      "create-outline",
      "fitness-outline",
      "bicycle-outline",
      "construct-outline",
      "person-outline",
      "document-outline",
      "medical-outline",
      "school-outline",
      "scale-outline",
      "flower-outline",
      "build-outline",
      "desktop-outline",
      "add-circle-outline",
      "laptop-outline",
      "tablet-portrait-outline",
      "tablet-landscape-outline",
      "business-outline",
      "card-outline",
      "people-outline",
      "walk-outline",
      "sparkles-outline",
      "hand-left-outline",
      "gift-outline",
      "chatbubble-outline",
      "brush-outline",
      "calendar-outline",
      "shirt-outline",
      "flask-outline",
      "globe-outline",
    ],
  },
  {
    name: "Sports",
    icons: [
      "pulse-outline",
      "medal-outline",
      "bicycle-outline",
      "boat-outline",
      "locate-outline",
      "heart-outline",
      "basketball-outline",
      "barbell-outline",
      "walk-outline",
      "footsteps-outline",
      "heart-dislike-outline",
      "infinite-outline",
      "baseball-outline",
      "football-outline",
      "tennisball-outline",
      "snow-outline",
      "accessibility-outline",
      "trail-sign-outline",
      "golf-outline",
      "bowling-ball-outline",
      "water-outline",
      "fitness-outline",
      "trophy-outline",
    ],
  },
  {
    name: "Health & Fitness",
    icons: [
      "fitness-outline",
      "heart-outline",
      "pulse-outline",
      "barbell-outline",
      "walk-outline",
      "bicycle-outline",
      "water-outline",
      "leaf-outline",
      "medical-outline",
      "nutrition-outline",
      "restaurant-outline",
      "bed-outline",
      "moon-outline",
      "sunny-outline",
      "body-outline",
      "footsteps-outline",
    ],
  },
  {
    name: "Learning",
    icons: [
      "book-outline",
      "library-outline",
      "school-outline",
      "document-text-outline",
      "create-outline",
      "pencil-outline",
      "code-slash-outline",
      "laptop-outline",
      "desktop-outline",
      "bulb-outline",
      "newspaper-outline",
      "journal-outline",
      "bookmarks-outline",
    ],
  },
  {
    name: "Lifestyle",
    icons: [
      "home-outline",
      "bed-outline",
      "restaurant-outline",
      "cart-outline",
      "cafe-outline",
      "wine-outline",
      "musical-notes-outline",
      "film-outline",
      "tv-outline",
      "headset-outline",
      "game-controller-outline",
      "brush-outline",
      "shirt-outline",
      "construct-outline",
      "car-outline",
      "airplane-outline",
    ],
  },
  {
    name: "Social",
    icons: [
      "people-outline",
      "person-outline",
      "chatbubble-outline",
      "call-outline",
      "mail-outline",
      "hand-left-outline",
      "gift-outline",
      "heart-outline",
      "star-outline",
      "sparkles-outline",
      "share-social-outline",
      "notifications-outline",
    ],
  },
];

// Flatten all icons for search
export const allIcons = iconCategories.flatMap((category) => category.icons);

// Remove duplicates
export const uniqueIcons = Array.from(new Set(allIcons));
